# Generated by Django 5.1.4 on 2025-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_construction', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='Note for under construction mode..', null=True)),
                ('uc_durartion', models.DateTimeField(blank=True, help_text='End date and time for under construction..', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
